#!/usr/bin/python

import os
import sys

def new_name(file):
    splited=os.path.splitext(file)
    return '.'.join([splited[0],'png'])

files = sys.argv[1:]

for file in files:
    os.system('convert "%s" "%s"' % (file, new_name(file)))
